server:
  port: 8001
  servlet:
    context-path: pro
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://192.168.159.19:8162:61617
    pool:
      enabled: true
      max-connections: 10

queueName: publish.queue
topicName: publish.topic
