server:
  port: 5566
spring:
  activemq:
    broker-url: tcp://192.168.159.19:61617
    user: admin
    password: admin
  jms:
    # 目的地是queue还是topic， false（默认） = queue    true =  topic
    pub-sub-domain: true

  #  自定义主题名称
mytopic: boot-activemq-topic
